projectBuilding:

  commonSettings:

    selectiveExecutions:

      StaticPreview:

        tasksAndSourceFilesSelection:

          markupProcessing: [ StaticPreview, Pages ]
          stylesProcessing: [ AllStylesForStaticPreview ]

        browserLiveReloadingSetupID: StaticPreview

      Application:

        tasksAndSourceFilesSelection:

          markupProcessing: [ SingePageApplicationEntryPoint ]
          stylesProcessing: [ SharedStylesForApplication ]
          ECMA_ScriptLogicProcessing: [ ClientEntryPoint, FrontServerEntryPoint ]

        browserLiveReloadingSetupID: Application


  markupProcessing:

    staticPreview:

      stateDependentPagesVariationsSpecificationFileRelativePath: 01-Source/Implementation/Elements/Client/StaticPreview/PagesStateDependentVariations.yaml

      importsFromCompiledTypeScript:

        files:
          - importedNamespace: MockData
            sourceFileRelativePath: 01-Source/Implementation/Elements/Client/StaticPreview/_MockData/MockData.ts
            outputDirectoryRelativePath: 01-Source/Implementation/Elements/Client/StaticPreview/_MockData


    entryPointsGroups:

      StaticPreview:

        topDirectoryRelativePath: 01-Source/Implementation/Elements/Client/StaticPreview
        partialsRecognition:
          excludeSubdirectoriesWithPrefixes: "_"
          excludeFilesWithPrefixes: "_"

        buildingModeDependent:
          STATIC_PREVIEW:
            outputTopDirectoryRelativePath: 02-StaticPreviewBuild

      Pages:

        topDirectoryRelativePath: 01-Source/Implementation/Elements/Client/Pages
        partialsRecognition:
          excludeSubdirectoriesWithPrefixes: "_"
          excludeFilesWithPrefixes: "_"

        buildingModeDependent:
          STATIC_PREVIEW:
            outputTopDirectoryRelativePath: 02-StaticPreviewBuild

      SingePageApplicationEntryPoint:

        singleEntryPointRelativePath: 01-Source/Implementation/Elements/Client/index.pug
        buildingModeDependent:
          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: 03-LocalDevelopmentBuild/public
          PRODUCTION:
            outputTopDirectoryRelativePath: 06-ProductionBuild/public


  stylesProcessing:

    entryPointsGroups:

      AllStylesForStaticPreview:

        singleEntryPointRelativePath: 01-Source/Implementation/Elements/Client/StaticPreview/AllStyles.styl
        buildingModeDependent:
          STATIC_PREVIEW:
            outputTopDirectoryRelativePath: 02-StaticPreviewBuild

      SharedStylesForApplication:

        singleEntryPointRelativePath: 01-Source/Implementation/Elements/Client/SharedAssets/Styles/SharedStyles.styl
        buildingModeDependent:
          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: 03-LocalDevelopmentBuild/public
          PRODUCTION:
            outputTopDirectoryRelativePath: 06-ProductionBuild/public

  ECMA_ScriptLogicProcessing:

    common:

    entryPointsGroups:

      ClientEntryPoint:

        singleEntryPointRelativePath: 01-Source/Implementation/Elements/Client/ClientEntryPoint.ts

        targetRuntime:
          type: BROWSER

        associatedMarkupEntryPointsGroupID_ForModulesDynamicLoadingWithoutDevelopmentServer: SingePageApplicationEntryPoint
        buildingModeDependent:
          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: 03-LocalDevelopmentBuild/public
          PRODUCTION:
            outputTopDirectoryRelativePath: 06-ProductionBuild/public

      FrontServerEntryPoint:

        singleEntryPointRelativePath: 01-Source/Implementation/Elements/FrontServer/FrontServerEntryPoint.ts

        targetRuntime:
          type: NODEJS
          minimalVersion:
            major: 16

        buildingModeDependent:
          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: 03-LocalDevelopmentBuild
          PRODUCTION:
            outputTopDirectoryRelativePath: 06-ProductionBuild


  browserLiveReloading:

    setups:

      StaticPreview:

        localServer:

          rootDirectoryRelativePath: 02-StaticPreviewBuild
          customStartingFileNameWithExtension: StaticPreviewAnywherePage.html

      Application:

        localServer:

          rootDirectoryRelativePath: 03-LocalDevelopmentBuild/public
          customStartingFileNameWithExtension: index.html
